---
apiVersion: tf.tungsten.io/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: tf
spec:
  commonConfiguration:
    hostNetwork: true
  services:
    analyticsSnmp:
      metadata:
        labels:
          tf_cluster: cluster1
        name: analyticssnmp1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
          cassandraInstance: configdb1
          rabbitmqInstance: rabbitmq1
          configInstance: config1
          containers:
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
          - name: analytics-snmp-collector
            image: contrail-analytics-snmp-collector
          - name: analytics-snmp-topology
            image: contrail-analytics-snmp-topology
    analyticsAlarm:
      metadata:
        labels:
          tf_cluster: cluster1
        name: analyticsalarm1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
          cassandraInstance: configdb1
          rabbitmqInstance: rabbitmq1
          configInstance: config1
          containers:
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
          - name: analytics-alarm-gen
            image: contrail-analytics-alarm-gen
          - name: kafka
            image: contrail-external-kafka
    cassandras:
    - metadata:
        labels:
          tf_cluster: cluster1
        name: configdb1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          configInstance: config1
          containers:
          - name: cassandra
            image: contrail-external-cassandra
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
    kubemanagers:
    - metadata:
        labels:
          tf_cluster: cluster1
        name: kubemanager1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
          cassandraInstance: configdb1
          rabbitmqInstance: rabbitmq1
          configInstance: config1
          ipFabricForwarding: false
          ipFabricSnat: true
          hostNetworkService: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          containers:
          - name: kubemanager
            image: contrail-kubernetes-kube-manager
    rabbitmq:
      metadata:
        labels:
          tf_cluster: cluster1
        name: rabbitmq1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          containers:
          - name: rabbitmq
            image: contrail-external-rabbitmq
    webui:
      metadata:
        labels:
          tf_cluster: cluster1
        name: webui1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          configInstance: config1
          controlInstance: control1
          cassandraInstance: configdb1
          logLevel: SYS_DEBUG
          containers:
          - name: redis
            image: contrail-external-redis
          - name: webuijob
            image: contrail-controller-webui-job
          - name: webuiweb
            image: contrail-controller-webui-web
    zookeepers:
    - metadata:
        labels:
          tf_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          containers:
            - name: zookeeper
              image: contrail-external-zookeeper
